<div id='AddGreyNavWrapper'>
        	<table id='GreyNavTable' cellpadding='0' cellspacing='0'>
                <tr><td colspan='11' width='500' height='4'><img src='http://claus.net.ua/art/aimg/avwr/navr/GreyToolbar_01.png' width='500' height='4'></td></tr>
                <tr><td width='126' height='33'><img src='http://claus.net.ua/art/aimg/avwr/navr/GreyToolbar_02.png' width='126' height='33'></td>
            		<td width='27' height='33'><img src='http://claus.net.ua/art/aimg/avwr/navr/brownButtonLeft_03.jpg' width='27' height='33' id='btn16' onMouseDown="MM_swapImage('btn16','','http://claus.net.ua/art/aimg/avwr/navr/brownButtonLeftDown_03.jpg',1)" onMouseOver="MM_swapImage('btn16','','http://claus.net.ua/art/aimg/avwr/navr/brownButtonLeftOver_03.jpg',1)" onMouseOut="MM_swapImgRestore()"></td>
                    <td width='32' height='33'><img src='http://claus.net.ua/art/aimg/avwr/navr/GreyToolbar_04.png' width='32' height='33'></td>
                    <td width='30' height='33'><img src='http://claus.net.ua/art/aimg/avwr/navr/brownButtonLeft_02.jpg' width='30' height='33' id='btn17' onMouseDown="MM_swapImage('btn17','','http://claus.net.ua/art/aimg/avwr/navr/brownButtonLeftDown_02.jpg',1)" onMouseOver="MM_swapImage('btn17','','http://claus.net.ua/art/aimg/avwr/navr/brownButtonLeftOver_02.jpg',1)" onMouseOut="MM_swapImgRestore()"></td>
                	<td width='18' height='33'><img src='http://claus.net.ua/art/aimg/avwr/navr/GreyToolbar_06.png' width='18' height='33'></td>
                	<td width='34' height='33'><img src='http://claus.net.ua/art/aimg/avwr/navr/brownButtonCenter_01.jpg' width='34' height='33' id='btn18' onMouseDown="MM_swapImage('btn18','','http://claus.net.ua/art/aimg/avwr/navr/brownButtonCenterDown_01.jpg',1)" onMouseOver="MM_swapImage('btn18','','http://claus.net.ua/art/aimg/avwr/navr/brownButtonCenterOver_01.jpg',1)" onMouseOut="MM_swapImgRestore()"></td>
                	<td width='18' height='33'><img src='http://claus.net.ua/art/aimg/avwr/navr/GreyToolbar_08.png' width='18' height='33'></td>
                	<td width='30' height='33'><img src='http://claus.net.ua/art/aimg/avwr/navr/brownButtonRight_02.jpg' width='30' height='33' id='btn19' onMouseDown="MM_swapImage('btn19','','http://claus.net.ua/art/aimg/avwr/navr/brownButtonRightDown_02.jpg',1)" onMouseOver="MM_swapImage('btn19','','http://claus.net.ua/art/aimg/avwr/navr/brownButtonRightOver_02.jpg',1)" onMouseOut="MM_swapImgRestore()"></td>
                	<td width='31' height='33'><img src='http://claus.net.ua/art/aimg/avwr/navr/GreyToolbar_10.png' width='31' height='33'></td>
                	<td width='27' height='33'><img src='http://claus.net.ua/art/aimg/avwr/navr/brownButtonRight_03.jpg' width='27' height='33' id='btn20' onMouseDown="MM_swapImage('btn20','','http://claus.net.ua/art/aimg/avwr/navr/brownButtonRightDown_03.jpg',1)" onMouseOver="MM_swapImage('btn20','','http://claus.net.ua/art/aimg/avwr/navr/brownButtonRightOver_03.jpg',1)" onMouseOut="MM_swapImgRestore()"></td>
                	<td width='127' height='33'><img src='http://claus.net.ua/art/aimg/avwr/navr/GreyToolbar_12.png' width='127' height='33'></td></tr>
                <tr><td colspan='11'  width='500' height='9'><img src='http://claus.net.ua/art/aimg/avwr/navr/GreyToolbar_13.png' width='500' height='9'></td></tr>
        	</table>
</div>